### PR TITLE
fix: Add missing service name to the replay publish topic

### LINKED ISSUE #65: Replay publish topic missing service
When replay publishes the Events, the multi-level topic is missing the service name

### PR DESCRIPTION
**Pull request by lenny-intel**
closes #65

**If your build fails**  due to your commit message not passing the build checks, please review the guidelines here: https://github.com/edgexfoundry/app-record-replay/blob/main/.github/CONTRIBUTING.md

## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [x] I am not introducing a new dependency (add notes below if you are)
- [x] I have added unit tests for the new feature or bug fix (if not, why?)
- [x] I have fully tested (add details below) this the new feature or bug fix (if not, why?)
- [ ] I have opened a PR for the related docs change (if not, why?)
  <link to docs PR>

## Testing Instructions
Record data from Device Virtual
Replay the data and verify the replayed data is published to `edgex/events/device-virtual/#`

### CODE REVIEW

File: internal/application/manager.go [hunk 1]
```diff
@@ -567,3 +595,15 @@ func (m *dataManager) processBatchedData(_ appInterfaces.AppFunctionContext, dat
...
 	return false, nil
 }
+
+func (m *dataManager) getServiceName(deviceName string) string {
+	m.recordingMutex.Lock()
+	defer m.recordingMutex.Unlock()
+
+	device := m.recordedData.Devices[deviceName]
+	if device == nil {
+		return "unknown-service"
```
Comment (jim-wang-intel) [inline internal/application/manager.go:605]: why this special name? cannot return empty string?

Comment (lenny-intel) [reply internal/application/manager.go:605]: Need to be non-empty name for the multi-level topic. It should never occur since all devices were loaded prior to this, so this is just CYA.

Comment (jim-wang-intel) [reply internal/application/manager.go:605]: ok

**Review by jim-wang-intel — APPROVED** [review]
LGTM
